version: "3"
services: 
  postgres:
    image: postgres:13.3
    ports: 
      - "4001:5432"
    environment: 
      - POSTGRES_USER=bima
      - POSTGRES_DB=MenuOrder
      - POSTGRES_PASSWORD=12345678
  redis:
    image: redis:6-alpine
    ports: 
      - "4002:6379"
  pgadmin:
    image: dpage/pgadmin4:5.5
    ports: 
      - "4003:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=bima@local.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
